### ISSUE TITLE
Serde json error: expected value at line 1 column 1

### ISSUE THREAD

**Issue by agemooij** [databricks/click#62]
After setting up and connecting to a remote K8s cluster from my kubectl config, I'm getting deser errors for all commands like `pods`, `deployments`, etc.

```
Serde json error: expected value at line 1 column 1
```

What does this mean?

**Comment by azazel75** [comment]
Doing the same thing I got instead this one:
```
Serde json error: trailing characters at line 1 column 5 is:closed
```
kubectl work flawlessly
the cluster has version 1.12.2

**Comment by xbaran** [comment]
Same problem here with `namespaces`. K8S 1.14.1

**Comment by xbaran** [comment]
Well, there is a problem with kubernetes API running on subcontext.

Lets say Rancher k8s distribution runs kubernetes API at `https://rancher.company.co/k8s/clusters/local`. 
To access namespaces enpoint click will join `/api/namespaces` with API endpoint but that will produce `https://rancher.company.co/api/namespaces` instead of `https://rancher.company.co/k8s/clusters/local/api/namespaces` and eventually it will produce 404 -page not found. At last Click will interpret this as error - `Serde json error: trailing characters at line 1 column 5 is:closed`

**Comment by nicklan** [comment]
This should be fixed by now (long time after report I know). Please re-open if you see anything like this.
